# specs/agents/base.agent.spec.yaml
apiVersion: v1alpha1
kind: AgentSpecification
metadata:
  name: base-agent
  version: 1.0.0
  labels:
    type: abstract
    framework: duulair

spec:
  interface:
    required_methods:
      - name: initialize
        input:
          schema: ConfigSchema
        output:
          type: boolean
        description: Initialize agent with configuration
      
      - name: process
        input:
          schema: MessageSchema
        output:
          schema: ResponseSchema
        description: Process incoming message
      
      - name: getCapabilities
        output:
          type: array
          items:
            type: string
        description: List agent capabilities

  traits:
    - name: observable
      methods:
        - getMetrics
        - getHealth
        - getLogs
    
    - name: stateful
      methods:
        - saveState
        - loadState
        - clearState
    
    - name: collaborative
      methods:
        - communicate
        - delegate
        - coordinate

  schemas:
    ConfigSchema:
      type: object
      required: [name, role]
      properties:
        name:
          type: string
        role:
          type: string
        model:
          type: string
          default: claude-3-haiku-20240307
        temperature:
          type: number
          default: 0.7
        maxTokens:
          type: integer
          default: 1000
    
    MessageSchema:
      type: object
      required: [content, context]
      properties:
        id:
          type: string
        content:
          type: string
        context:
          $ref: '#/schemas/ContextSchema'
        metadata:
          type: object
    
    ContextSchema:
      type: object
      properties:
        userId:
          type: string
        patientId:
          type: string
        sessionId:
          type: string
        timestamp:
          type: string
          format: date-time
        source:
          type: string
          enum: [line, api, n8n, system]

  lifecycle:
    startup:
      - validate_config
      - connect_services
      - load_state
      - register_handlers
    
    shutdown:
      - save_state
      - cleanup_resources
      - notify_peers